apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-cache
  namespace: chris-builds
spec:
  # storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: build-cache
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi